// STORED PROCEDURE STATUS
export const SP_STATUS = {
  SUCCESS: 1,
  VALIDATION_FAIL: 0,
  ERROR: -1,
};


// HTTP STATUS
export const HTTP = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
};


// ADMIN ACTION TYPE (optional clarity)
// export const ADMIN_ACTION = {
//   USER_APPROVAL: "USER_APPROVAL",
//   CAMPAIGN_APPROVAL: "CAMPAIGN_APPROVAL",
//   USER_BLOCK: "USER_BLOCK",
//   CAMPAIGN_BLOCK: "CAMPAIGN_BLOCK",
//   USER_REJECT: "USER_REJECT",
//   CAMPAIGN_REJECT: "CAMPAIGN_REJECT",
// };
